# Generated by Django 3.2 on 2023-04-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='license',
            field=models.CharField(choices=[(1, 'Device'), (2, 'User')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(choices=[('Power BI', 'PowerBI'), (2, 'Power Apps'), (3, 'Power Apps'), (4, 'Power Virtual Agents'), (5, 'Android'), (6, 'iOS'), (7, 'JavaScript'), (8, 'React'), (9, 'Django'), (10, 'DocuSign'), (11, 'Stripe')], max_length=50),
        ),
    ]
